// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "serenitea",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "serenitea",
            targets: ["AppModule"],
            bundleIdentifier: "com.serenitea",
            teamIdentifier: "JZNPKB7CRS",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .microphone(purposeString: "Sereni-tea wants to hear you blowing to the mic so you can  cool down your tea :)")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)